sudo: required
dist: trusty
group: edge

language: node_js

os:
  - linux

node_js:
  - '6'
  - '5'
  - '4'

before_install:
  - npm --version

after_success:
  - npm run coveralls
  - npm run coverage-clean
